"""create messages tabe

Revision ID: 8e960d3f0590
Revises: 9416f3140ab0
Create Date: 2025-06-30 21:22:25.386838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e960d3f0590'
down_revision = '9416f3140ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
